server:
  port: 8772
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: provider-log2
  data:
    mongodb:
      database: eureka
      host: 127.0.0.1
      port: 27017


