server:
  port: ${port:8762}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: provider-logss
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: maven
